-- MySQL Script generated by MySQL Workbench
-- Mon May 22 14:26:25 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bqudkckamwnwpg4znjug
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bqudkckamwnwpg4znjug
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bqudkckamwnwpg4znjug` DEFAULT CHARACTER SET utf8 ;
USE `bqudkckamwnwpg4znjug` ;

-- -----------------------------------------------------
-- Table `bqudkckamwnwpg4znjug`.`habitaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bqudkckamwnwpg4znjug`.`habitaciones` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(255) NOT NULL,
  `tipo` VARCHAR(255) NULL,
  `valor` VARCHAR(255) NULL,
  PRIMARY KEY (`codigo`));


-- -----------------------------------------------------
-- Table `bqudkckamwnwpg4znjug`.`reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bqudkckamwnwpg4znjug`.`reservas` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `codigo_habitacion` INT NOT NULL,
  `nombre_cliente` VARCHAR(255) NOT NULL,
  `telefono_cliente` VARCHAR(100) NOT NULL,
  `fecha_reservacion` DATE NOT NULL,
  `fecha_entrada` DATE NOT NULL,
  `fecha_salida` DATE NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_reservas_habitaciones_idx` (`codigo_habitacion` ASC) VISIBLE,
  CONSTRAINT `fk_reservas_habitaciones`
    FOREIGN KEY (`codigo_habitacion`)
    REFERENCES `bqudkckamwnwpg4znjug`.`habitaciones` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `bqudkckamwnwpg4znjug`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bqudkckamwnwpg4znjug`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(255) NOT NULL,
  `apellido` VARCHAR(255) NOT NULL,
  `estado` TINYINT(1) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `bqudkckamwnwpg4znjug`.`usuario_auth`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bqudkckamwnwpg4znjug`.`usuario_auth` (
  `fk_usuarios_id` INT NOT NULL,
  `contraseña` VARCHAR(255) NOT NULL,
  `fecha_registro` DATETIME NOT NULL,
  INDEX `fk_usuario_auth_usuarios1_idx` (`fk_usuarios_id` ASC) VISIBLE,
  PRIMARY KEY (`fk_usuarios_id`),
  CONSTRAINT `fk_usuario_auth_usuarios1`
    FOREIGN KEY (`fk_usuarios_id`)
    REFERENCES `bqudkckamwnwpg4znjug`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
